#!/bin/bash

echo "Starting..."

sudo pkill memcached
sudo pkill gdb
sudo pkill loader
sudo pkill screen

./stop_share

cd /dev/shm/
sudo rm *
cd
cd /mydata/memcached_scoreBased/
make clean
make

./init_share 15600

sudo screen -S MEM_SESSION -X quit
sudo screen -dmS MEM_SESSION

sudo screen -S MEM_SESSION -X exec sudo gdb -ex=r --args memcached -u root -p 11212 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn2
sudo screen -S MEM_SESSION -p winn2 -X exec sudo gdb -ex=r --args memcached -u root -p 11213 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn3
sudo screen -S MEM_SESSION -p winn3 -X exec sudo gdb -ex=r --args memcached -u root -p 11214 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn4
sudo screen -S MEM_SESSION -p winn4 -X exec sudo gdb -ex=r --args memcached -u root -p 11215 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn5
sudo screen -S MEM_SESSION -p winn5 -X exec sudo gdb -ex=r --args memcached -u root -p 11216 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn6
sudo screen -S MEM_SESSION -p winn6 -X exec sudo gdb -ex=r --args memcached -u root -p 11217 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn7
sudo screen -S MEM_SESSION -p winn7 -X exec sudo gdb -ex=r --args memcached -u root -p 11218 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn8
sudo screen -S MEM_SESSION -p winn8 -X exec sudo gdb -ex=r --args memcached -u root -p 11219 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn9
sudo screen -S MEM_SESSION -p winn9 -X exec sudo gdb -ex=r --args memcached -u root -p 11220 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn10
sudo screen -S MEM_SESSION -p winn10 -X exec sudo gdb -ex=r --args memcached -u root -p 11221 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn11
sudo screen -S MEM_SESSION -p winn11 -X exec sudo gdb -ex=r --args memcached -u root -p 11222 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn12
sudo screen -S MEM_SESSION -p winn12 -X exec sudo gdb -ex=r --args memcached -u root -p 11223 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn13
sudo screen -S MEM_SESSION -p winn13 -X exec sudo gdb -ex=r --args memcached -u root -p 11224 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn14
sudo screen -S MEM_SESSION -p winn14 -X exec sudo gdb -ex=r --args memcached -u root -p 11225 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn15
sudo screen -S MEM_SESSION -p winn15 -X exec sudo gdb -ex=r --args memcached -u root -p 11226 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn16
sudo screen -S MEM_SESSION -p winn16 -X exec sudo gdb -ex=r --args memcached -u root -p 11227 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn17
sudo screen -S MEM_SESSION -p winn17 -X exec sudo gdb -ex=r --args memcached -u root -p 11228 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn18
sudo screen -S MEM_SESSION -p winn18 -X exec sudo gdb -ex=r --args memcached -u root -p 11229 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn19
sudo screen -S MEM_SESSION -p winn19 -X exec sudo gdb -ex=r --args memcached -u root -p 11230 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn20
sudo screen -S MEM_SESSION -p winn20 -X exec sudo gdb -ex=r --args memcached -u root -p 11231 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn21
sudo screen -S MEM_SESSION -p winn21 -X exec sudo gdb -ex=r --args memcached -u root -p 11232 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn22
sudo screen -S MEM_SESSION -p winn22 -X exec sudo gdb -ex=r --args memcached -u root -p 11233 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn23
sudo screen -S MEM_SESSION -p winn23 -X exec sudo gdb -ex=r --args memcached -u root -p 11234 -t 4 -m 4096 -n 550 -G

sudo screen -S MEM_SESSION -X screen -t winn24
sudo screen -S MEM_SESSION -p winn24 -X exec sudo gdb -ex=r --args memcached -u root -p 11235 -t 4 -m 4096 -n 550 -G

echo "24 Instances now online.. Listening on PORTs: 11212 TO 11235"

cd ../benchmarks

sudo screen -S AMH_SESSION -X quit 
sudo screen -dmS AMH_SESSION

sudo screen -S AMH_SESSION -X exec sudo ./2g-normal/benchmark

sudo screen -S AMH_SESSION -X screen -t win2
sudo screen -S AMH_SESSION -p win2 -X exec sudo ./22g-normal/benchmark

sudo screen -S AMH_SESSION -X screen -t win3
sudo screen -S AMH_SESSION -p win3 -X exec sudo ./3g-normal/benchmark

sudo screen -S AMH_SESSION -X screen -t win4
sudo screen -S AMH_SESSION -p win4 -X exec sudo ./4g-normal/benchmark

sudo screen -S AMH_SESSION -X screen -t win5
sudo screen -S AMH_SESSION -p win5 -X exec sudo ./44g-normal/benchmark

sudo screen -S AMH_SESSION -X screen -t win6
sudo screen -S AMH_SESSION -p win6 -X exec sudo ./5g-loop/benchmark

sudo screen -S AMH_SESSION -X screen -t win7
sudo screen -S AMH_SESSION -p win7 -X exec sudo ./6g-loop/benchmark

sudo screen -S AMH_SESSION -X screen -t win8
sudo screen -S AMH_SESSION -p win8 -X exec sudo ./7g-loop/benchmark

sudo screen -S AMH_SESSION -X screen -t win9
sudo screen -S AMH_SESSION -p win9 -X exec sudo ./8g-loop/benchmark

sudo screen -S AMH_SESSION -X screen -t win10
sudo screen -S AMH_SESSION -p win10 -X exec sudo ./9g-loop/benchmark

sudo screen -S AMH_SESSION -X screen -t win11
sudo screen -S AMH_SESSION -p win11 -X exec sudo ./10g-loop/benchmark

sudo screen -S AMH_SESSION -X screen -t win12
sudo screen -S AMH_SESSION -p win12 -X exec sudo ./222g-normal/benchmark

echo "All benchmarks triggered"
